# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_created=True)),
                ('serial_number', models.CharField(max_length=40)),
                ('tag', models.CharField(blank=True, max_length=20)),
                ('model', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('keywords', models.CharField(blank=True, max_length=150)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_itens', to='devices.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.Type'),
        ),
    ]
